name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU # build for multi-platform support
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push # don't need to use actions/checkout because the action uses Git context
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: imcalvin/mittens:latest
      - name: POST to Portainer
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
