name: Portainer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # clones the repository's code into the runner environment where the pipeline is executed
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: imcalvin/mittens:latest

      - name: Deploy to Portainer
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.PORTAINER_API_TOKEN }}" \
          -d '{"Image": "imcalvin/mittens:latest"}' \
            https://portainer.bxian03.systems/api/endpoints/${{env.PORTAINER_ENDPOINT_ID}}/stacks/${{env.STACK_NAME}}?endpointId=1
